### ISSUE TITLE
KeyError when event is missing a summary

### ISSUE THREAD

**Issue by barrucadu** [icydoge/Constantine#1] opened 2017-03-14 20:53 UTC
```
Reading settings.json...
Reading this week's calendar events...
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    event_item['what'] = utils.tex_escape(event['summary'])
KeyError: 'summary'
```

**Comment by chongyangshi** [comment] 2017-03-14 22:04
Cannot reproduce error but preemptively addressed by skipping events missing the required tags, if that ever happens in Google's JSON.

**Closed as completed by chongyangshi** 2017-03-14 22:04 UTC
